### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by thorrak** [N3MIS15/ESP32-Tilt-Repeater#3]
Hey there!

I currently maintain a project called [BrewFlasher](http://www.brewflasher.com/) which simplifies the process of flashing brewing-related firmware to ESP8266 and ESP32-based microcontrollers and had a user ask about potentially getting this firmware added to the list that BrewFlasher supports. That said, I wanted to reach out to you as there currently is no licensing information for this project and before I build a precompiled binary for BrewFlasher to provide, I want to be sure that you're OK with this.

Do you have a preferred license for this project (MIT, for example)?

**Comment by N3MIS15** [comment]
I have no will to license this script. Do with it as you wish.

**Comment by thorrak** [comment]
> I have no will to license this script. Do with it as you wish.

Thanks, I appreciate it!
